/**
 * @file main.h
 * @brief Main definitions for MSPM0G3507 Synthesizer
 * 
 * Global types, constants, and state structures
 * 
 * @version 1.3.0
 * @date 2025-12-18
 * @note GPIO definitions now generated by SysConfig
 */

#ifndef MAIN_H_
#define MAIN_H_

#include <stdint.h>
#include <stdbool.h>
#include "ti_msp_dl_config.h" 

//=============================================================================
// SYSTEM CONSTANTS
//=============================================================================


#define SYSCLK_FREQUENCY 80000000
#define SAMPLE_RATE         8000        // 8 kHz audio sample rate
#define SENSOR_UPDATE_HZ    20          // 20 Hz sensor polling
#define DISPLAY_UPDATE_HZ   10          // 10 Hz display refresh

// NOTE: GPIO PORT and PIN definitions are generated by SysConfig
// See Debug/ti_msp_dl_config.h for actual pin assignments

//=============================================================================
// LCD LAYOUT CONSTANTS
//=============================================================================

#define LCD_MARGIN_LEFT     5
#define LCD_MARGIN_RIGHT    5
#define LCD_LINE_HEIGHT     20
#define LCD_CHAR_HEIGHT     8

// Y-positions for display elements
#define LCD_Y_TITLE         5
#define LCD_Y_FREQ          25
#define LCD_Y_WAVEFORM      45
#define LCD_Y_VOLUME        95
#define LCD_Y_VOLUME_BAR    105
#define LCD_Y_STATUS        130
#define LCD_Y_HELP1         145
#define LCD_Y_HELP2         155

//=============================================================================
// SYNTHESIZER PARAMETERS
//=============================================================================

// Frequency range
#define FREQ_MIN            20.0f       // 20 Hz
#define FREQ_MAX            2000.0f     // 2 kHz
#define FREQ_DEFAULT        440.0f      // A4 note

// Volume range
#define VOLUME_MIN          0
#define VOLUME_MAX          100
#define VOLUME_DEFAULT      50

// Pitch bend range (semitones)
#define PITCH_BEND_RANGE    2.0f

// Joystick ADC calibration (12-bit ADC: 0-4095)
#define JOY_ADC_MIN         0
#define JOY_ADC_MAX         4095
#define JOY_ADC_CENTER      2048
#define JOY_DEADZONE        100

// Accelerometer calibration
#define ACCEL_ZERO_G        2048

// Timer wrap-around handling
#define TIMER_MAX_VALUE     0xFFFFFFFFUL
#define TIMER_ELAPSED(now, prev) ((now) >= (prev) ? ((now) - (prev)) : (TIMER_MAX_VALUE - (prev) + (now)))

// Clamp macro
#define CLAMP(x, min, max) ((x) < (min) ? (min) : ((x) > (max) ? (max) : (x)))

//=============================================================================
// ENUMERATIONS
//=============================================================================

typedef enum {
    WAVE_SINE = 0,
    WAVE_SQUARE,
    WAVE_SAWTOOTH,
    WAVE_TRIANGLE,
    WAVE_COUNT
} Waveform_t;

typedef enum {
    MODE_SYNTH = 0,
    MODE_THEREMIN,
    MODE_DRUM
} Mode_t;

//=============================================================================
// STATE STRUCTURES
//=============================================================================

typedef struct {
    // Audio parameters
    volatile Waveform_t waveform;
    volatile Mode_t mode;
    volatile float frequency;
    volatile uint8_t volume;
    volatile int8_t pitchBend;
    volatile bool audio_playing;
    
    // UI flags
    volatile bool display_update_needed;
    
    // Joystick inputs (volatile - modified in ISR)
    volatile uint16_t joy_x;
    volatile uint16_t joy_y;
    volatile bool joy_pressed;
    
    // Button states (volatile - modified in ISR)
    volatile bool btn_s1;
    volatile bool btn_s2;
    
    // Accelerometer (volatile - modified in ISR)
    volatile uint16_t accel_x;
    volatile uint16_t accel_y;
    volatile uint16_t accel_z;
    
    // Microphone level (volatile - modified in ISR)
    volatile uint16_t mic_level;
    
    // Light sensor
    volatile float light_lux;
    
} SynthState_t;

//=============================================================================
// GLOBAL VARIABLES (defined in main.c)
//=============================================================================

extern SynthState_t g_synthState;

//=============================================================================
// FUNCTION PROTOTYPES
//=============================================================================

// Utility functions
void delay_ms(uint32_t milliseconds);
void delay_us(uint32_t microseconds);

#endif // MAIN_H_