/**
 * @file main.h
 * @brief Main definitions for MSPM0G3507 Synthesizer
 * 
 * Global types, constants, and state structures
 * 
 * @version 1.3.0
 * @date 2025-12-18
 * @note GPIO definitions now generated by SysConfig
 */

#ifndef MAIN_H_
#define MAIN_H_

#include <stdint.h>
#include <stdbool.h>

//=============================================================================
// SYSTEM CONSTANTS
//=============================================================================

#define SYSCLK_FREQUENCY    32000000UL  // 32 MHz (simplified clock)
#define SAMPLE_RATE         8000        // 8 kHz audio sample rate
#define SENSOR_UPDATE_HZ    20          // 20 Hz sensor polling

// NOTE: GPIO PORT and PIN definitions are generated by SysConfig
// See Debug/ti_msp_dl_config.h for actual pin assignments

//=============================================================================
// LCD LAYOUT CONSTANTS
//=============================================================================

#define LCD_MARGIN_LEFT     5
#define LCD_MARGIN_RIGHT    5
#define LCD_LINE_HEIGHT     20
#define LCD_CHAR_HEIGHT     8

// Y-positions for display elements
#define LCD_Y_TITLE         5
#define LCD_Y_FREQ          25
#define LCD_Y_WAVEFORM      45
#define LCD_Y_VOLUME        95
#define LCD_Y_VOLUME_BAR    105
#define LCD_Y_STATUS        130
#define LCD_Y_HELP1         145
#define LCD_Y_HELP2         155

//=============================================================================
// SYNTHESIZER PARAMETERS
//=============================================================================

// Frequency range
#define FREQ_MIN            20.0f       // 20 Hz
#define FREQ_MAX            2000.0f     // 2 kHz
#define FREQ_DEFAULT        440.0f      // A4 note

// Volume range
#define VOLUME_MIN          0
#define VOLUME_MAX          100
#define VOLUME_DEFAULT      50

// Pitch bend range (semitones)
#define PITCH_BEND_RANGE    2.0f

// ADC calibration (12-bit ADC)
#define ADC_MAX             4095
#define ADC_CENTER          2048
#define ADC_DEADZONE        100

// Wavetable size
#define WAVETABLE_SIZE      256

//=============================================================================
// ENUMERATIONS
//=============================================================================

typedef enum {
    WAVE_SINE = 0,
    WAVE_SQUARE,
    WAVE_SAWTOOTH,
    WAVE_TRIANGLE,
    WAVE_COUNT
} WaveformType;

//=============================================================================
// STATE STRUCTURES
//=============================================================================

typedef struct {
    // Audio state
    volatile float frequency;
    volatile uint8_t volume;
    volatile WaveformType waveform;
    volatile bool audio_playing;
    
    // Control inputs (volatile because modified in ISR)
    volatile uint16_t joy_x;
    volatile uint16_t joy_y;
    volatile uint16_t mic_level;
    
    // Phase accumulator (volatile because modified in ISR)
    volatile uint32_t phase_accumulator;
    volatile uint32_t phase_increment;
    
    // UI state flags (volatile for ISR safety)
    volatile bool ui_needs_update;
    volatile uint32_t last_ui_update;
    
    // Sensor update timing
    volatile uint32_t last_sensor_update;
    
} SynthState;

//=============================================================================
// GLOBAL VARIABLES (defined in main.c)
//=============================================================================

extern SynthState g_synthState;
extern int16_t g_wavetable[WAVETABLE_SIZE];

//=============================================================================
// FUNCTION PROTOTYPES
//=============================================================================

// Initialization
void init_wavetable(WaveformType waveform);
void init_system(void);

// Audio processing
void update_phase_increment(void);
int16_t get_wavetable_sample(void);

// Control processing
void process_joystick(void);
void process_buttons(void);

// Display updates
void update_display(void);
void draw_waveform_preview(uint8_t x, uint8_t y, uint8_t width, uint8_t height, WaveformType waveform);

// Utility
void delay_ms(uint32_t ms);

#endif // MAIN_H_